-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "country" TEXT NOT NULL DEFAULT 'NL',
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'EUR',
ADD COLUMN     "defaultTaxRate" DOUBLE PRECISION NOT NULL DEFAULT 0.21,
ADD COLUMN     "estimateCounter" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "estimateYear" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "iban" TEXT,
ADD COLUMN     "invoiceCounter" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "invoiceYear" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "locale" TEXT NOT NULL DEFAULT 'nl-NL',
ADD COLUMN     "vatNumber" TEXT;

-- AlterTable
ALTER TABLE "Customer" ADD COLUMN     "vatNumber" TEXT;

-- AlterTable
ALTER TABLE "Estimate" ADD COLUMN     "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0.21;

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0.21;
